//
//  UserInfoRouter.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/16/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserInfoRouter: UserInfoWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = UserInfoViewController(nibName: nil, bundle: nil)
        let interactor = UserInfoInteractor()
        let router = UserInfoRouter()
        let presenter = UserInfoPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    static func createModuleWithNav() -> UINavigationController{
        let view = createModule()
        let nav = UINavigationController()
        nav.navigationBar.tintColor = .white
        nav.navigationBar.barStyle = .black
        nav.viewControllers = [view]
        return nav
    }
}
