//
//  UserInfoPresenter.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/16/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserInfoPresenter: UserInfoPresenterProtocol {

    weak private var view: UserInfoViewProtocol?
    var interactor: UserInfoInteractorProtocol?
    private let router: UserInfoWireframeProtocol

    init(interface: UserInfoViewProtocol, interactor: UserInfoInteractorProtocol?, router: UserInfoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func setUserData(user: UserModel) {
        view?.setUserData(user: user)
    }
    
    func getUserData() {
        interactor?.getUserData()
    }
    
    func logOut() {
        interactor?.logOut()
    }
}
