//
//  LoginProtocols.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/16/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol LoginPresenterProtocol: class {
    func loginUser(login: String, password: String)
    func loginOK()
    func showMessage(message: String)
}

//MARK: Interactor -
protocol LoginInteractorProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
    func loginUser(login: String, password: String)
}

//MARK: View -
protocol LoginViewProtocol: class {
    
    var presenter: LoginPresenterProtocol?  { get set }
    func loginOk()
    func showMessage(message: String)
}
