//
//  LoginViewController.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/16/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: SuperViewController, LoginViewProtocol {
    @IBOutlet weak var loginTF: UITextField!
    @IBOutlet weak var passwordTF: UITextField!
    
	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func loginAction(_ sender: Any) {
        let passEmpty = isEmptyTF(passwordTF)
        let loginEmpty = isEmptyTF(loginTF)
        guard !loginEmpty, !passEmpty else {return}
        
        let login = loginTF.text!
        let password = passwordTF.text!
        
        self.presenter?.loginUser(login: login, password: password)
    }
    
    func loginOk() {
        
        let appDelegate = UIApplication.shared.delegate
        guard let window = appDelegate?.window! else {return}
        UIView.transition(with: window, duration: 0.3, options: .transitionFlipFromLeft, animations: {
            window.rootViewController = UserInfoRouter.createModuleWithNav()
        }, completion: nil)
    }
    
    func showMessage(message: String) {
        alertOK(text: message)
    }
}
