//
//  EditInfoRouter.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/17/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class EditInfoRouter: EditInfoWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> EditInfoViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = EditInfoViewController(nibName: nil, bundle: nil)
        let interactor = EditInfoInteractor()
        let router = EditInfoRouter()
        let presenter = EditInfoPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
