//
//  EditInfoProtocols.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/17/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol EditInfoWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol EditInfoPresenterProtocol: class {
    func updateUser(user: EditUser)
    func showMessage(message: String)
    func updateOk()
    func getUser() -> UserModel?
}

//MARK: Interactor -
protocol EditInfoInteractorProtocol: class {
    
    var presenter: EditInfoPresenterProtocol?  { get set }
    func updateUser(user: EditUser)
    func getUser() -> UserModel?
}

//MARK: View -
protocol EditInfoViewProtocol: class {
    
    var presenter: EditInfoPresenterProtocol?  { get set }
    func showMessage(message: String)
    func updateOk()
}
