//
//  EditInfoPresenter.swift
//  githubExanple
//
//  Created George Kyrylenko on 12/17/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class EditInfoPresenter: EditInfoPresenterProtocol {
    
    weak private var view: EditInfoViewProtocol?
    var interactor: EditInfoInteractorProtocol?
    private let router: EditInfoWireframeProtocol

    init(interface: EditInfoViewProtocol, interactor: EditInfoInteractorProtocol?, router: EditInfoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func updateUser(user: EditUser) {
        interactor?.updateUser(user: user)
    }
    
    func showMessage(message: String) {
        view?.showMessage(message: message)
    }
    
    func updateOk() {
        view?.updateOk()
    }
    
    func getUser() -> UserModel? {
        return interactor?.getUser()
    }

}
